### ISSUE TITLE
"あとでかく"部分の修正

### ISSUE THREAD

**Issue by c0b2315233** [c0b23036a5/ProjExD_3#1]
https://github.com/c0b23036a5/ProjExD_3/blob/ad9ec75236ddcc3a6d0af952ea68d509999c8f6d/fight_kokaton.py#L127
"あとでかく"を書いておいてください

**Comment by c0b23036a5** [comment]
"あとでかく"の部分を
"こうかとんが吐き出すビームを表示するためのクラス"に変更しました。
